# Allow Travis to run this project in container
sudo: false
language: node_js
node_js:
  # Latest stable version
  - node
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - "node_modules"
notifications:
  slack:
    secure: Xtq6NAQ/5vG1V51qpWq9DAZku+l3YlxslU+vUXn98Vk01EZTi5eFewxIj+Cx+lrdHwP2ItslQTxl5cowGGhZussZquhXEQACuoy3p/tSck+wASkyDBmGuDC7IS8Tc0dh5VeS7fXEZFNotD+a8JYCMLs8uzBfZQSFJE40Y0KyS7MeG8i6c8tRzy5f1kw1B5RgwWIW33ySOKiVpiSe7toke6nDBUg7AU0YwOJFMs9Ej9CavjqLMnpl9v5h332326mGh2/NgqbesrwgLf6YQ6yJT1Uwo805GK8rPJ+3fG8nfVU6bJP6KYUitumrL4hdw91uC2IAHa7/WmFMDyLxh9ab3J1LtWbIsK5IIBvMLEkihsNbhl4PopbV3YSqdqcEYGWQDrFQYj3cN8Md3k+j97jvfQb6N5dEoeUBU3riUEfiTgAfVHEJOdHwafr8zLOdLQv/jmkWBX/R2FUjnK97jTUydNqwM0bKMjYwr8GiE/+HPtnET0WW3ZwAZYgWpR4mhpKASAvt/FoI7SL+sf88Yavp9EuJZNZeJ0jpgJrvJ/qQJ82FJj5yd1fkwSZZ0J9ltnLHM8f6QLvury0fKzd7KHT7BwYogaFQBQIZ/7wVM/WH+Ae9j2eA3x7+P8fzM+N5PO7ZnlTNKsMNYmKThO/cNkPOsHJtjgE31vP9F9zTeV9MbSE=
  email:
    on_success: never
    on_failure: never
before_install:
  # Copy environment variables file to prevent error
  - cp .env.example .env
  # Install GreenKeeper lockfile tool
  - npm install -g greenkeeper-lockfile@1
install: npm install
before_script: greenkeeper-lockfile-update
script:
  - npm test
  - npm run docs
after_script: greenkeeper-lockfile-upload
after_success:
  # Send test coverage to Coveralls
  - "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
  # Send test coverage to Codacy
  - "./node_modules/.bin/nyc report --reporter=lcovonly && cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage"
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
